# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [7]:
import pandas as pd
import numpy as np
ccpfile = pd.read_csv("./data/ccp_current_csv.csv")
ccpfile

STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW              Madison St (N)   
15         Underwood Pl       NW            North Capitol St   
16              20th St       NW                 Columbia Rd   
17          Quintana Pl       NE                      3rd St   
18         Tuckerman St       NE                  Kansas Ave   
19              Eads St       NE                     45th St   
20               4th St       SE                  Newcomb St   
21              Belt Rd       NW                  Jenifer St   
22            Oneida St       NE           New Hampshire Ave   
23      Carrollsburg Pl       SW                        O St   
24              23rd St       NW          Washington Cir (N)   
25           Kanawha St       NW                    Utah Ave   
26      Piney Branch Rd       NW                Underwood St   
27              30th St       NW               Stephenson Pl   
28              32nd St       NW                 Woodland Dr   
29              33rd St       NW            Broad Branch Ter   
..                  ...      ...                         ...   
435      New Jersey Ave       NW                        F St   
436             15th St       NE                     Ames Pl   
437     East Capitol St       BN                        C St   
438         Randolph St       NE                     25th Pl   
439    South Dakota Ave       NE                Delafield St   
440          Wheeler Rd       SE                 Congress St   
441      New Jersey Ave       NW                        H St   
442     Mount Olivet Rd       NE               Brentwood Pky   
443              Oak St       NW                     16th St   
444        Michigan Ave       NE                     14th St   
445                C St       NE                     20th St   
446        Virginia Ave       SE                  6th St (S)   
447              Oak St       NW                Brown St (N)   
448         Florida Ave       NE                New York Ave   
449  North Carolina Ave       NE         East Capitol St (E)   
450            Elder St       NW                      8th St   
451          Benning Rd       SE                        G St   
452           School St       SW                      4th St   
453             18th St       NW                        M St   
454       Longfellow St       NW                     16th St   
455             10th St       NW                        M St   
456          Woodley Rd       NW             Connecticut Ave   
457          Woodley Rd       NW           Cathedral Ave (E)   
458              3rd St       SW            Independence Ave   
459             16th St       NW                 Primrose Rd   
460          Woodley Rd       NW                  Woodley Pl   
461         Western Ave       NW         Chevy Chase Cir (E)   
462             49th St       NW                   Fulton St   
463       Quackenbos St       NE           New Hampshire Ave   
464    North Capitol St       BN  Hawaii Ave  Rock Creek Chu   

                 TOINTERSECTION  NOOFBLOCKS     

### 3.1.a  what is its shape and what does that mean?

In [6]:
ccpfile.shape

(465, 27)

In [ ]:
It means that it has 465 rows and 27 columns

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [ ]:
465
 

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [13]:
a = np.array([ 1, 2, 3, 4])
b = np.array([ 5, 6, 7, 8])

In [14]:
a + b

array([ 6,  8, 10, 12])

In [20]:
np.add(a,b)

array([ 6,  8, 10, 12])

### 3.3.2 subtraction a-b

In [15]:
a-b

array([-4, -4, -4, -4])

In [21]:
np.subtract(a,b)

array([-4, -4, -4, -4])

### 3.3.3 multiplication a*b

In [16]:
a * b

array([ 5, 12, 21, 32])

In [22]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

### 3.3.4 divsion a/b

In [17]:
a/b

array([0, 0, 0, 0])

In [23]:
np.divide(a,b)

array([0, 0, 0, 0])

### 3.3.5 modulo  a%b

In [18]:
a%b

array([1, 2, 3, 4])

In [25]:
np.mod(a,b)

array([1, 2, 3, 4])

### 3.3.6 power  a^b

In [28]:
a ** b

array([    1,    64,  2187, 65536])

In [26]:
np.power(a,b)

array([    1,    64,  2187, 65536])

## Homework 3.4
Find your own data and load it into a dataframe

In [1]:
%matplotlib notebook

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
roads = pd.read_csv("./data/Roads_2015.csv")


## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [2]:
roads['DESCRIPTION'].value_counts()

Road                      14448
Intersection               7844
Parking Lot                6214
Paved Drive                3311
Alley                      3215
Paved Median Island        1414
Unpaved Median Island      1135
Unpaved Traffic Island      858
Paved Traffic Island        523
Hidden Road                 449
Hidden Median               125
Name: DESCRIPTION, dtype: int64

In [3]:
roads['DESCRIPTION'].value_counts().plot(kind = 'bar')

<IPython.core.display.Javascript object>